'use client'

import type { Metadata } from 'next'
import Layout from '@/components/features/Layout'
import { Global, css } from '@emotion/react'
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
import { GraphBaseUrl } from '@/helpers/general';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const client = new ApolloClient({
  uri: GraphBaseUrl,
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Global
        styles={css`
          body {
            margin: 0;
          }
        `}
      />
      <ApolloProvider client={client}>
        <body>
          <Layout>
            {children}
          </Layout>
        </body>
      </ApolloProvider>
    </html>
  )
}
