'use client'

import type { Metadata } from 'next'
import Layout from '@/components/features/Layout'
import { Global, css } from '@emotion/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Global
        styles={css`
          body {
            margin: 0;
          }
        `}
      />
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
